### ISSUE TITLE
Unable to devtools::install_github("antonioggsousa/micrUBIfuns")

### ISSUE THREAD

**Issue by chuynh96** [antonioggsousa/micrUBIfuns#2] opened 2022-01-13 01:05 UTC
Hello,

I was having an issue with running devtools::install_github("antonioggsousa/micrUBIfuns") as it doesn't appear to be working.
I am getting the following error when I run devtools::install_github("antonioggsousa/micrUBIfuns"):

Downloading GitHub repo antonioggsousa/micrUBIfuns@HEAD
Skipping 2 packages not available: ComplexHeatmap, phyloseq
✓  checking for file ‘/private/var/folders/ps/0f_zbw8j4s500hv_2qyzt95h0000gn/T/RtmpESWGgZ/remotes46aa16367ebe/antonioggsousa-micrUBIfuns-a37d476/DESCRIPTION’ ...
─  preparing ‘micrUBIfuns’:
✓  checking DESCRIPTION meta-information ...
─  excluding invalid files
   Subdirectory 'R' contains invalid file names:
     ‘.main.R’
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted ‘LazyData’ from DESCRIPTION
─  building ‘micrUBIfuns_0.1.0.tar.gz’
   
ERROR: dependency ‘ComplexHeatmap’ is not available for package ‘micrUBIfuns’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/micrUBIfuns’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/ps/0f_zbw8j4s500hv_2qyzt95h0000gn/T//RtmpESWGgZ/file46aa53baf756/micrUBIfuns_0.1.0.tar.gz’ had non-zero exit status

This error is also causing the library("micrUBIfuns") to not work, but I am not sure how to fix this.
Any help on this would be great, thank you!

~ Mai

**Comment by antonioggsousa** [comment] 2022-01-13 06:14
Hello Mai, 

Thank you for your interest on `micrUBIfuns` package. 

The problem is related with two dependencies that you need to install first as it appears in the error message that you're getting: 

> Skipping 2 packages not available: ComplexHeatmap, phyloseq

These packages are `ComplexHeatmap` and `phyloseq`. 

Therefore, try to install first these packages and only then the `micrUBIfuns` package. 

To install `ComplexHeatmap` from its github repository do (according to this [resource](https://jokergoo.github.io/ComplexHeatmap-reference/book/)): `devtools::install_github("jokergoo/ComplexHeatmap")`

To install `phyloseq` from its github repository do (according to this [resource](https://joey711.github.io/phyloseq/install.html)): `devtools::install_github("phyloseq/joey711")`. 

Finally, if you're able to install both packages without any problem, please try to install `micrUBIfuns` by typing: `devtools::install_github("antonioggsousa/micrUBIfuns")`

Please let me know if this worked for you. 

Best regards, 

António

**Comment by chuynh96** [comment] 2022-01-13 14:13
Thank you very much! Was able to fix it with the following:

install.packages("remotes")
devtools::install_github("jokergoo/ComplexHeatmap", force = TRUE)
devtools::install_github("antonioggsousa/micrUBIfuns", force = TRUE)
source("https://raw.githubusercontent.com/joey711/phyloseq/master/inst/scripts/installer.R",
       local = TRUE)
install_phyloseq(branch = "github")
library(remotes)
library("micrUBIfuns")

~ Mai

**Comment by antonioggsousa** [comment] 2022-01-13 15:12
Thank you for letting me know. 

I'll close the issue then. 

Best regards, 

António

**Closed as completed by antonioggsousa** 2022-01-13 15:12 UTC
